# Generated by Django 5.1.4 on 2024-12-29 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('social_media_links', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('portfolio', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
