# Generated by Django 5.1.4 on 2024-12-29 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_order_orderitem_delete_customuser_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_artist', models.BooleanField(default=False)),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('social_media_links', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
